### PR TITLE
Updated roster table styles for consistency.

### PR DESCRIPTION
**Pull request by dsjen**
sandbox

Iterative improvements!

@dan-f please review

### CODE REVIEW

**Comment by dsjen** [comment]
There was an update to backgrid-filter, which includes a typo in a dependency resulting in an error with bower install.  I'll submitted a https://github.com/wyuenho/backgrid-filter/pull/46 to fix this.  I'll give the repo owner a day or two and will otherwise update our package reference in order to unblock us.

**Comment by dan-f** [comment]
:+1: :clap:

**Comment by dsjen** [comment]
Ok, incremental progress.  The `lunr` issue is fixed, but the backbone resolution issue has now emerged.

**Comment by dsjen** [comment]
@dan-f -- finally, a passing build!  I needed to specify a version of backbone for resolution and use the non-minified version of backgrid because the minified one seems to have been removed from the latest distribution.

**Comment by dan-f** [comment]
Alright!!

**Pull request merged**
