### PR TITLE
Fixed run_coverage.sh

### PR DESCRIPTION
**Pull request by dsjen**
This fixes the coverage step of the travis build (e.g. https://api.travis-ci.org/jobs/196994983/log.txt?deansi=true): 

`/edx/app/insights/edx_analytics_dashboard/.travis/run_coverage.sh: line 5: cd: /edx/app/insights/insights: No such file or directory`

@feanil -- please let me know if this was needed for some reason!

### CODE REVIEW

**Comment by dsjen** [comment]
@feanil -- codecov reports: "No coverage uploaded for pull request base (master@101f835)."  Do you know if that is related to the change in this PR?  It seems that because our master builds have been failing (maybe b/c of the `cd` to a non-existant directory issue?) that there isn't a report to compare against.

**Comment by feanil** [comment]
@dsjen I corrected the path in run_tests.sh but failed to do this in run_coverage.sh.

I think the right thing to do is to cd to the `/edx/app/insights/edx_analytics_dashboard` directory instead.

**Review by feanil — APPROVED** [review]

**Comment by dsjen** [comment]
@feanil -- thanks!  I updated that and see the codecov checks have passed, although it's a bit odd that coverage increased on the project (+2.17%).  I'll take it though!

@thallada -- please review!

**Review by thallada — APPROVED** [review]
:+1:

**Pull request merged**
