### PR TITLE
Evaluate DOCUMENTATION_LOAD_ERROR_MESSAGE at the end of production settings.

### PR DESCRIPTION
**Pull request by dsjen**
@rocha @clintonb

### CODE REVIEW

**Comment by rocha** [comment]
:rocket: (did you have an acceptance test for this?, if not that is fine, just checking if that also requires to be updated).

**Comment by dsjen** [comment]
No acceptance test :(

**Comment by rocha** [comment]
That is fine, I think this is something transitory while we figure a better solution.

**Comment by dsjen** [comment]
FYI, there's a ticket to have a fake course be served up with no data, so that we can test out the no data pages at some point.

**Pull request merged**
