### PR TITLE
UI: Static Prototype Templates

### PR DESCRIPTION
**Pull request by talbs**
This work involves getting a first pass of basic Bootstrap-based static templates rendering, including:
- simple template -re-organization
- engagement, enrollment, performance, and base dashboard-like view HTML + placeholder content
- basic edX theming/customization of Bootstrap UI
- adding holder.js vendor utility for image/interactive placeholder UI
- additional small custom UI tweaks (animations, layout tweaking, iconography)
- styles 404 and 500 system templates

### CODE REVIEW

**Comment by talbs** [comment]
@rocha, @dsjen, and @clintonb, here's the bulk of getting all of the views in the Insight Prototype rendering using Bootstrap's UI with some tweaks/extremely light theming.

A few known issues:
- I've created very static .html files that need a home in the view logic (they are currently in the `templates/courses/` dir)
- @dsjen, I still can't get the Bootstrap JS (referenced in the bottom of base.html) to load, so the dropdowns and any canned behavior that relies on that is still untested at this point
- The course-based navigation is repeated in all templates and needs to be abstracted (there's a big `TODO:` in the code.
- I've added in holder.js for placeholder images/areas - you should remove that once you're good on the real rendering

---

@rocha, if you can be the merge usher when this is ready, that would again be appreciated :)

---

@dsjen, assuming you're going to wire these up, I'm happy to walk through what I've done and where things are to complete this quick hand-off. Shout when you have time (I'll be off on vacation next wee as an FYI).

**Comment by rocha** [comment]
We have to ask @mulby since I don't have permissions. Also, lets see what happens tomorrow at the :heart: gerrit :heart: meeting.

**Comment by dsjen** [comment]
This looks good to me!  I saw it live and am excited to see start working with it.

**Comment by talbs** [comment]
Thanks, @dsjen! 

@mulby can I get some love and support in :truck:ing this fella to Mergetown?

**Comment by mulby** [comment]
Yup, I'll take it from here!

**Comment by talbs** [comment]
Danka!

**Comment by clintonb** [comment]
Damn fine work! :+1:

**Comment by mulby** [comment]
All set.

**Pull request merged**
