### PR TITLE
updates link to access partner help

### PR DESCRIPTION
**Pull request by lamagnifica**
## [DOC-2366](https://openedx.atlassian.net/browse/DOC-2366)

Updates the link to partner help.
### Date Needed

30 Oct 2015
### Reviewers
- [ ] Subject matter expert: @JAAkana 
- [ ] Subject matter expert: @sstack22
- [x] Doc team review (sanity check): @mhoeber
### Testing
- [x] Ran make html without warnings or errors
### Post-review
- [ ] Squash commits

### CODE REVIEW

**Comment by mhoeber** [comment]
:+1:  thanks.  could you though move the links to the main links file and include that file in preface?

**Comment by mhoeber** [comment]
oh never mind, this is not doc repo.

**Comment by JAAkana** [comment]
I can't tell, but I'm assuming this is for only edx.org and edge.edx.org. 

If so, then looks good! :palm_tree:

**Comment by lamagnifica** [comment]
@JAAkana there is currently only one _Using edX Insights_ guide, and it's for partners. Future work will create two guides, one for partners and a separate one for OS. Until then, everyone who's reading will see the same thing.

**Pull request merged**
