### PR TITLE
replaced static with dynamically generated copyright year

### PR DESCRIPTION
**Pull request by shailysangwan**
https://openedx.atlassian.net/browse/DOC-3212
with reference to the [outreachy page](https://openedx.atlassian.net/wiki/display/COMM/Outreachy+Round+13)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shailysangwan! I've created [OSPR-1434](https://openedx.atlassian.net/browse/OSPR-1434) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-analytics-dashboard/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by shailysangwan** [comment]
Is the Travis CI build failing because of my commit?
I don't understand, can someone please help me find the error?

**Comment by gsong** [comment]
@shailysangwan Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for a simple change in this case, but we're hoping you would make future contributions as well.

**Comment by gsong** [comment]
@shailysangwan The CI error isn't related to this PR, so don't worry about it.

**Comment by shailysangwan** [comment]
I've sent the CA document to legal@edx.org

**Comment by gsong** [comment]
@shailysangwan Awesome. I'll keep an eye out for a notice from legal once they've processed your agreement.

**Comment by shaunagm** [comment]
@lamagnifica

(Also, @shailysangwan, your agreement has been processed.)

**Comment by lamagnifica** [comment]
Hi @shailysangwan in addition to the automated tests, please also test out your changes locally. This gives you a chance to look at the rendered HTML and make sure that the result is what you expect. 
In this repo, you can open a command prompt and go to the directory of the guide you want to build (dashboard).
Enter the "make clean" and then the "make html" commands.
The resulting html files will be in a build directory in the dashboard directory.

**Comment by lamagnifica** [comment]
Apologies, I clicked the wrong button...!

**Comment by shailysangwan** [comment]
What does the awaiting prioritization flag mean?
Is any work pending from my side?

**Comment by shaunagm** [comment]
@shailysangwan Good question!  "Awaiting prioritization" means we've given the PR to an internal team to review, and that they've not yet prioritized when they'll get to it.  There's nothing needed from you besides patience -- we'll get to it soon.  :)

**Comment by lamagnifica** [comment]
Hi @shailysangwan the one thing you could do is perform the manual test I suggested above and then comment on how it looks to you here (or provide a screen shot, or however you'd like to describe the result).

**Comment by shailysangwan** [comment]
@lamagnifica I've built the HTML, and the result looks fine.
The files in which I changed the state of the copyright year from static to dynamic remain the same as they were before, and the year appears in those in which it was absent.

I had a question though.
I was looking at `en_us/ORA2/source/conf.py`, and if I changed the copyright text to something other than edX Inc, the docs reflected that change, but if I deleted the copyright line, it still stayed there in the built page.
I tried changing some other `conf.py` files to see what was causing this, and it seems that the configuration file in `en_us/shared` is like a parent to all other configuration files with any matching options set in the configuration files at a lower level overriding those set in `shared/config.py`.
I'm just making a guess here, please confirm if this is the case.

If so, why are we adding the copyright separately in each of the `config.py` files?

**Comment by lamagnifica** [comment]
Thanks for testing and for investigating further, @shailysangwan. If you have found a simpler way to achieve the same goal -- and it sounds like you have -- please pursue it! 
AFAIK, there is a set of three different files/levels that can affect the appearance of the footer: 
edx-documentation/shared/conf.py, the individual, per-guide conf.py files (like 
edx-documentation/en_us/data/source/conf.py), and our customized Sphinx theme in
edx-documentation/en_us/_themes/edx_theme/footer.html

**Comment by lamagnifica** [comment]
👍

**Comment by shaunagm** [comment]
:thumbsup: from me as well!

**Pull request merged**
