### PR TITLE
Remove node_modules text from po files

### PR DESCRIPTION
**Pull request by IDerr**
Remove bad strings, node_modules string should not be included in the po file,
(It also tricks transifex users thinking there are some strings to translate)

Mentionning @edx/incr-reviewers as described in the documentation

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @IDerr! I've created [OSPR-6171](https://openedx.atlassian.net/browse/OSPR-6171) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by IDerr** [comment]
Just signed CLA

**Comment by natabene** [comment]
@IDerr Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Comment by natabene** [comment]
@IDerr Could you please look into failing tests?

**Comment by IDerr** [comment]
For sure, 
for the default CI, there's an error on the CI side, it misses the coverage command
image

for the commit lint, I'll take a look into it

**Comment by IDerr** [comment]
@natabene Is it possible to take a look at the default CI, it's missing a binary, which should not be on my part :)

Thanks

**Comment by IDerr** [comment]
Rebased on master, and fixed commit name and description 
@natabene if you can relaunch CI jobs, it would be great :D

**Comment by IDerr** [comment]
The CI job is still failing because I am modifying the i18n text, and it doesn't seems to like it, perhaps there's another way to reject node_modules text from getting included on transifex.

EDIT: I've seen that the command on the latest CI job (update translations): 
https://github.com/edx/edx-analytics-dashboard/runs/4061864447?check_suite_focus=true#step:10:46
```
python manage.py makemessages -l en -v1 '--ignore=docs/*' '--ignore=src/*' '--ignore=i18n/*' '--ignore=assets/*' '--ignore=static/bundles/*' -d djangojs
```
Is it not easier to just add ```--ignore=node_modules/* ``` ?

Thanks for your work

**Comment by IDerr** [comment]
Closing this PR in favor of https://github.com/edx/edx-analytics-dashboard/pull/1213

Seems a better way to fix this issue

**Comment by openedx-webhooks** [comment]
@IDerr Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-dashboard&entry.867055334=https://github.com/edx/edx-analytics-dashboard/pull/1207&entry.1484655318=https://github.com/IDerr&entry.752974735=2021-10-25+19:01&entry.1917517419=2021-11-02+17:45&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
