### PR TITLE
Corrected link to Developer's guide

### PR DESCRIPTION
**Pull request by lamagnifica**
@mhoeber , @stroilova

### CODE REVIEW

**Comment by mhoeber** [comment]
the link you have will work.  prefer to use:  http://edx.readthedocs.org/projects/edx-developer-guide/en/latest/ to make reporting easier.

http://edx.readthedocs.org/projects/userdocs/en/latest/ will now properly redirect to:  http://edx.readthedocs.org/projects/edx-developer-guide/en/latest/

**Comment by lamagnifica** [comment]
@mhoeber corrected link and title

**Comment by mhoeber** [comment]
:+1:

**Comment by stroilova** [comment]
:+1

**Pull request merged**
