### PR TITLE
EDUCATOR-442 Remove footer's feedback email and all references to it

### PR DESCRIPTION
**Pull request by kdmccormick**
Removes feedback email from Insights footer, as it was deemed redundant with the support email that's also there.

Also, we don't really check that email anymore, so we don't want it featured on the page.

[Ticket](https://openedx.atlassian.net/browse/EDUCATOR-442).

@edx/educator-dahlia

### CODE REVIEW

**Comment by thallada** [comment]
It looks like this change edits translatable text and the tests detected this and failed. If you run `make extract_translations` and `make compile_translations` and then commit the changes in `analytics_dashboard/conf/locale/` then the translation files will be up to date with your changes and those errors should go away.

**Comment by dsjen** [comment]
Thanks!  It's a small change, but just for some context, this helps in routing users to the right people.

Also, after this merges, we should probably remove the [references in the configuration repo](https://github.com/edx/configuration/search?utf8=%E2%9C%93&q=INSIGHTS_FEEDBACK_EMAIL&type=).

**Comment by thallada** [comment]
@dsjen's comment in your other PR reminded me that we have an [AUTHORS](https://github.com/edx/edx-analytics-dashboard/blob/master/AUTHORS) file too. Make sure to add yourself to that!

**Comment by kdmccormick** [comment]
@thallada I made your changes. Can I squash & merge once tests pass?

**Comment by kdmccormick** [comment]
@dsjen https://github.com/edx/configuration/pull/3894

**Review by thallada — APPROVED** [review]
Looks good to merge to me :+1:

**Pull request merged**
