### PR TITLE
First Pass at Packaging RequireJS Dependencies

### PR DESCRIPTION
**Pull request by clintonb**
@dsjen @rocha

### CODE REVIEW

**Comment by rocha** [comment]
@clintonb looks good to me. Are you going to address the TODOs before merging, or are those for a second pass?

**Comment by clintonb** [comment]
@rocha Those will be addressed in a future iteration. They are minor annoyances that I couldn't figure out how to get rid of.

**Comment by rocha** [comment]
Alright, rebase then :rocket:

**Comment by clintonb** [comment]
See #168. That implementation is much more developer-friendly.

**Pull request closed without merging**
