### PR TITLE
Run a11y tests with firefox to fix flaky acceptance tests.

### PR DESCRIPTION
**Pull request by dsjen**
Testing if this is flaky...

### CODE REVIEW

**Comment by dsjen** [comment]
4 tests have passed in a row since the FF switch.

screen shot 2017-01-31 at 1 08 53 pm

screen shot 2017-01-31 at 1 09 00 pm

I'm keeping my fingers crossed that this final run builds for 5 in a row.  This seems to have fixed the flakiness issue!

**Comment by dsjen** [comment]
@thallada -- seems like it passed!  Please review when you get the chance.

**Comment by thallada** [comment]
Thanks for fixing this! :smiley:

**Review by thallada — APPROVED** [review]

**Comment by dsjen** [comment]
Sure thing!  I can't wait for beautifully passing builds.

**Pull request merged**
