### PR TITLE
Using equirectangular map projection

### PR DESCRIPTION
**Pull request by clintonb**
Old
screen shot 2014-09-04 at 3 16 47 pm

New
screen shot 2014-09-04 at 3 28 42 pm

@marcotuts @dsjen @rocha @shnayder

### CODE REVIEW

**Comment by marcotuts** [comment]
:thumbsup:

**Comment by rocha** [comment]
Noooooooooo. I really don't like equirectangular, it is the Comic Sans of map projections.

Do you know if Winkel (7) or Eckert (5 or 6) are available? I like both, but prefer Eckert.

**Comment by shnayder** [comment]
I think this map library only has these two options, and I think equirectangular is better than Mercator.  At some point, we can get a better map.  Hackathon project? :)

**Comment by rocha** [comment]
But so ugly...

Almost everything is better than Mercator (which is pretty distorted), except equirectangular (which looks like somebody messed up the aspect ratio.

Seems like there are more here: https://github.com/d3/d3-geo-projection/

Anyway, not many people will care I guess. It is sort of when you care about typography and see something with bad kerning.

**Pull request merged**
