### PR TITLE
Update django-waffle to use clintonb's fix for django 1.8+

### PR DESCRIPTION
**Pull request by pomegranited**
Uses @clintonb 's `django-waffle==0.21.0` to fix errors when using `waffle_switch` and `waffle_flag` management commands.

**JIRA tickets**: OSPR

**Discussions**: cf https://github.com/jsocol/django-waffle/pull/244, [jsocol/django-waffle@v0.12.0](https://github.com/jsocol/django-waffle/commits/v0.12.0)

**Partner information**: 3rd party hosted 

**Deployment targets**: insights.edx.org, insights.stage.edx.org

**Merge deadline**: `open-releae/ginkgo.rc1`, if possible cc @nedbat 

**Testing instructions**:

1. Deploy Insights on an analytics devstack using the current master.
1. Try listing the waffle flags: 
    ```
    sudo su insights
    ./manage.py waffle_switch --list --settings=analytics_dashboard.settings.production
    ```
    Note `AttributeError: type object 'BaseCommand' has no attribute 'option_list'`
1. Checkout the branch from this PR: `jill/update-django-waffle`
1. Install the pip requirements to upgrade django-waffle:
   ```
   make requirements.py
   ```
1. Re-run the waffle_switch command from step 2, and note success.

**Reviewers**
- [ ] OpenCraft reviewer TBD
- [ ] edX reviewers TBD - @edx/analytics CC @thallada

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fedx-analytics-dashboard&number=706"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-1826](https://openedx.atlassian.net/browse/OSPR-1826) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-analytics-dashboard/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Review by clintonb — APPROVED** [review]
Looks good to me, but someone who actually manages/deploys this application should also sign off.

**Review by thallada — APPROVED** [review]
Thanks @pomegranited ! This looks good to me too :+1:

**Comment by thallada** [comment]
I'm going to merge this and then make a PR to cherry-pick this change into the ginkgo release branch.

**Comment by pomegranited** [comment]
Thank you @thallada and @clintonb !

**Pull request merged**
