### PR TITLE
[BD] Remove python 2.7 environment tests.

### PR DESCRIPTION
**Pull request by andrey-canon**
## Description 
Remove python 2.7 environment tests.
Part of .https://openedx.atlassian.net/browse/BOM-1360

### Reviewers
- [x] @morenol 
- [x]  Is this ready for edX's review? 
- [ ] @jmbowman 

 
### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @andrey-canon! I've created [OSPR-4284](https://openedx.atlassian.net/browse/OSPR-4284) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by morenol — APPROVED** [review]

**Comment by morenol** [comment]
Related to https://github.com/edx/configuration/pull/5703

**Review by jmbowman — APPROVED** [review]
Looks good once Insights on 3.5 is deemed stable in prod.

**Comment by jmbowman** [comment]
Travis is being problematic; going to try closing and reopening the PR to see if that correctly updates the status.

**Comment by jmbowman** [comment]
Switched this repo from the legacy travis-ci.org webhook to the travis-ci.com GitHub App, which is supposed to be more reliable.

**Pull request merged**
