### PR TITLE
Added course homepage

### PR DESCRIPTION
**Pull request by clintonb**
LMS will link to this page, so the LMS will not need to know about enrollment, engagement, etc.

### CODE REVIEW

**Comment by clintonb** [comment]
@rocha @dsjen

**Comment by rocha** [comment]
Test are failing, otherwise :shipit:

**Comment by clintonb** [comment]
Oops. Looks like our tests are talking to the API directly instead of mocking those calls.

**Comment by clintonb** [comment]
Test case updated to mock data.

**Pull request merged**
