### PR TITLE
fix: fixing GH workflow file syntax

### PR DESCRIPTION
**Pull request by mtyaka**
The codecov action syntax is not correct. This fixes it.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mtyaka!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @mtyaka - just checking in on this!

**Comment by mphilbrick211** [comment]
Hi @mtyaka! Do you plan to pursue this pull request? Just seeing if there are any updates?

**Comment by mtyaka** [comment]
Thanks for the ping @mphilbrick211 

The tests on this PR are failing for reasons unrelated to my code change and I won't have time to debug/fix that any time soon, so I am closing this PR for now.

**Comment by openedx-webhooks** [comment]
@mtyaka Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-analytics-dashboard&entry.867055334=https://github.com/openedx/edx-analytics-dashboard/pull/1458&entry.1484655318=https://github.com/mtyaka&entry.752974735=2023-05-25+12:30&entry.1917517419=2023-07-18+04:30&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
