### PR TITLE
Removed outline when hovering over links.

### PR DESCRIPTION
**Pull request by dsjen**
- outline is removed when hovering over links
- outline still exists in the drop down (unfortunately)

Previously with outline:
outline

Proposed update without outline:
no-outline

I didn't spend too much time on this and made a small improvement in removing the outline when hovering over links.

@rocha @clintonb @marcotuts @shnayder

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by marcotuts** [comment]
@dsjen  - can we make the hover color black (or whatever our nearly-black color is ) for Age/Education/Gender?

This would ideally also keep the blue hover color we use in the dark header for Activity/Demographics/Geography. 

Thanks for doing this!

**Comment by dsjen** [comment]
Using darkest gray: 
gray-link

**Comment by marcotuts** [comment]
:+1:

**Pull request merged**
