### PR TITLE
[SE-3950] Add a waffle flag to ignore the accept-language header.

### PR DESCRIPTION
**Pull request by Kelketek**
This pull request adds a waffle flag that makes the analytics system ignore the 'Accept-Language' header. The rationale is that while the Accept-Language header is presumed to communicate the user's preferred language, in practice many, perhaps most users do not set this value explicitly in their settings. This is a problem for installations that do not target English users as their primary audience.

When this flag is enabled, LANGUAGE_CODE is used to determine which translation to serve. An existing or future created cookie setting language preference will still work as expected.

**JIRA tickets**: https://openedx.atlassian.net/browse/OSPR-5367

**Dependencies**: None

**Merge deadline**: None

**Testing instructions**:

1. Clone the repository if you have not done so already.
2. Create a virtualenv with Python 3.5 and activate it.
3. Follow the installation instructions in the README.
4. Set ALLOWED_HOSTS to ['*'] to make things easier on yourself while testing.
5. Change the LANGUAGE_CODE setting to a language you'd prefer.
6. Use runserver. Observe that the language header is still respected.
7. Set the waffle flag with `./manage.py waffle_flag analytics_dashboard.ignore_accept_language --everyone --create`
8. Reload the page and verify the language has changed.

**Author notes and concerns**:

This does introduce the edx-toggle library, adding this waffle flag as the first documented to be used in this manner. It does not go back and add documentation for every existing waffle flag, which should probably be done at some point.

**Reviewers**
- [ ] @nizarmah 
- [ ] edX reviewer TBD

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Kelketek! I've created [OSPR-5367](https://openedx.atlassian.net/browse/OSPR-5367) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@edx/edx-data-engineering-admin Could you please review this OSPR? CC @macdiesel (Also please ensure this waffle flag is correctly documented).

**Comment by natabene** [comment]
@Kelketek Please let me know once it is ready for our review.

**Comment by Kelketek** [comment]
@natabene It will be a while-- we discovered a way to meet our clients needs without a code change like this, but since it also comes with the improvement of adding edx-toggle, we didn't want to close it out just yet. We're scheduling a task in our backlog to edit the PR a bit and make it a contribution once budget permits.

**Comment by nizarmah** [comment]
@Kelketek would you mind please closing this pull request since I opened a different one with the same purpose, https://github.com/edx/edx-analytics-dashboard/pull/1110?

**Comment by openedx-webhooks** [comment]
@Kelketek Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-dashboard&entry.867055334=https://github.com/edx/edx-analytics-dashboard/pull/1096&entry.1484655318=https://github.com/Kelketek&entry.752974735=2021-01-15+20:26&entry.1917517419=2021-03-08+15:00&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
