### PR TITLE
Upgraded to Django 1.7

### PR DESCRIPTION
**Pull request by clintonb**
@rocha @dsjen

### CODE REVIEW

**Comment by dsjen** [comment]
Very exciting!  Looks good to me.

**Comment by rocha** [comment]
@clintonb do you feel comfortable using a just released version? I don't think that we should update right now, I would give it a few months until Django 1.7 stabilizes a bit more.

**Comment by clintonb** [comment]
@rocha I see your point. Ordinarily I would wait; however, I see a couple advantages to upgrading now:
- No breaking changes for open source users (e.g. syncdb vs. migrate) in the future
- Better trimming of whitespace for translations (minor, I know)

Additionally, it is my understanding that the release candidates were pretty throughly reviewed. Obviously not all bugs will be caught; but, I am inclined to rely on the community.

**Comment by rocha** [comment]
Alright, those are good points. 1.7 has been in release candidate for a while, so lets hope all the critical bugs have been squeezed by now.

**Comment by clintonb** [comment]
Famous last words.

**Pull request merged**
