### PR TITLE
Change support link to email.

### PR DESCRIPTION
**Pull request by dsjen**
screen shot 2015-10-21 at 4 52 50 pm

@dan-f 

FYI: @shnayder @lamagnifica

### CODE REVIEW

**Comment by lamagnifica** [comment]
:+1:

**Comment by shnayder** [comment]
:ship:

**Comment by shnayder** [comment]
The fact that you had to change 10 files is a bit scary...

**Comment by dsjen** [comment]
No one is more shocked about that than me.

**Comment by dan-f** [comment]
:+1:

**Pull request merged**
