### PR TITLE
[BD] Upgrade edx-drf-extensions.

### PR DESCRIPTION
**Pull request by andrey-canon**
## Description 
Upgrade edx-drf-extensions.
Part of .https://openedx.atlassian.net/browse/BOM-1360

### Reviewers
- [x] @morenol 
- [x]  Is this ready for edX's review? 
- [ ] @jmbowman 
 
### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @andrey-canon! I've created [OSPR-4208](https://openedx.atlassian.net/browse/OSPR-4208) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by morenol — APPROVED** [review]

**Review by jmbowman — COMMENTED** [review]
Just one more thing we discovered when upgrading this in edx-platform: you need to set `JWT_AUTH_HEADER_PREFIX` to "JWT" since drf-jwt changed the default value and we rely on the old one.  This should have been in the edx-drf-extensions release notes, I'll add it there.

* https://github.com/edx/edx-platform/pull/23248/files#diff-82bda515879c96ab0641bfcbe58631c3R3430
* https://github.com/Styria-Digital/django-rest-framework-jwt/commit/bdf66fc07f257ac34e044aa165275b1139eeeca8#diff-c2e88bd1b487509c042387cf6af005a6L47

**Comment by morenol** [comment]
@jmbowman I saw that there is not a JWT setting on analytics_dashboard django settings. Should that be added? or that is something that needs to be added directly on your .yml service configs

**Review by jmbowman — APPROVED** [review]
Yes, this should be fine; I'm not sure we're even using JWT tokens in this service, but this at least makes sure we won't forget this if we start to do so.

**Pull request merged**
