### PR TITLE
Updated answer distribution labels.

### PR DESCRIPTION
**Pull request by dsjen**
- updated chart tooltip
- updated randomized chart message

@rocha @clintonb @lamagnifica

### CODE REVIEW

**Comment by lamagnifica** [comment]
question: does a different tip get shown if a problem includes only one part? that was the intention...

**Comment by dsjen** [comment]
The tip is the same for multiple problem as it is for one problem.  What is the desired tip for one problem?

**Comment by lamagnifica** [comment]
If you go to https://openedx.atlassian.net/wiki/display/AN/Labels+and+Tooltips+-+Insights and search for "1/14/15 AH" you'll see that I updated both this tip and the tip for problems that only have one part...

**Comment by rocha** [comment]
:+1:

**Comment by clintonb** [comment]
:+1:

**Pull request merged**
