### PR TITLE
Don't use -e in requirements.

### PR DESCRIPTION
**Pull request by feanil**
The -e is only needed for requirements that need to be locally editable, I don't think any of the
requirements here fall into that category.

Review: @dsjen @clintonb

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by dsjen** [comment]
:+1:

**Comment by feanil** [comment]
All tests seem to be failing with the same error:

`ImportError: No module named constants`  Any idea what that's about or which requirement it might be coming from?

**Comment by dsjen** [comment]
That seems to be coming from our own analyticsclient, https://github.com/edx/edx-analytics-data-api-client/tree/master/analyticsclient/constants.  That's odd that it's failing.  Do you need help digging into it?

**Comment by feanil** [comment]
Maybe we can look at it tomorrow.  I'll see if I can re-produce it locally.

**Comment by clintonb** [comment]
There was a connectivity issue at Travis. Tests are now passing. Merging.

**Comment by feanil** [comment]
@clintonb it wasn't a connectivity issue, I had to add the '-e' back in for 'edx-analytics-data-api-client' which to me suggests that the setup.py for that might not be installing correctly for non '-e' installs.  Can you add a ticket to your backlog to investigate that and get rid of the last '-e'?

**Pull request merged**
