### PR TITLE
Updated learner analytics from switch to flag.

### PR DESCRIPTION
**Pull request by dsjen**
- upgraded waffle
- changed enable_learner_analytics to display_learner_analytics

This PR upgrades waffle and changes enabling LA from a switch to a flag, which enables us to turn on this functionality for a percentage of users.

@ajpal @thallada

### CODE REVIEW

**Comment by thallada** [comment]
Cool, this should fix our waffle usage in django 1.9 too. I was just trying to fix it.

LGTM :+1:

**Comment by dsjen** [comment]
@thallada -- that's great!  Here's to incrementally addressing tech debt!

**Comment by dsjen** [comment]
Getting github connectivity errors...rerunning...again.

**Comment by dsjen** [comment]
Oh my!  `fatal: The remote end hung up unexpectedly`.  Restarting...

**Comment by ajpal** [comment]
👍

**Pull request merged**
