### PR TITLE
Geography tiles

### PR DESCRIPTION
**Pull request by clintonb**
Review/merge #97 first.

Design: https://projects.invisionapp.com/d/main#/console/1392015/31133496/preview

Screenshot
screen shot 2014-09-15 at 3 46 26 pm

Screenshot (without truncation)
screen shot 2014-09-15 at 3 32 51 pm

Question for @marcotuts: What are your thoughts on truncation? The unequal heights can be fixed CSS/JS, but it may be difficult (e.g. another couple hours of work). Thoughts on this?

@dsjen @rocha @marcotuts @shnayder

### CODE REVIEW

**Comment by shnayder** [comment]
I'm ok with the truncation. We'll also shorten the card titles as part of
the ui strings review.

Cc: @lamagnifica

**Comment by lamagnifica** [comment]
What we have for the three geo tiles: Top Country, Second Country, Third Country
https://openedx.atlassian.net/wiki/display/AN/UI+Strings+and+Tooltips+-+Insights
We could also drop "total" from "Total Countries Represented" without any loss of comprehension imo.

**Comment by clintonb** [comment]
Updated rankings with and without "Total"

screen shot 2014-09-16 at 11 19 43 am
screen shot 2014-09-16 at 11 21 04 am

Updated code currently does _not_ have "Total".

@shnayder @lamagnifica

**Comment by lamagnifica** [comment]
:+1: :dancers: 
The intention is for the full country name to appear on mouseover of the name, while our tool tip for the metric tile will appear when you mouse over the "i" icon, correct?

**Comment by clintonb** [comment]
@lamagnifica Yes. I have not been told otherwise.

**Comment by lamagnifica** [comment]
awesome!

**Pull request merged**
