### PR TITLE
Added Context-Sensitive Help

### PR DESCRIPTION
**Pull request by clintonb**
The help link in the navbar now points to the various course pages.

@rocha @dsjen @lamagnifica

### CODE REVIEW

**Comment by lamagnifica** [comment]
@clintonb would you please provide a sandbox?

**Comment by clintonb** [comment]
@lamagnifica I've invested about 45 minutes into attempting to update my sandbox to no avail. This code simply changes the help link to point to the appropriate page at http://edx-insights.readthedocs.org/en/latest/. If you have a few minutes I'd be happy to show you the functionality on my local machine.

**Comment by lamagnifica** [comment]
What I would look for in the sandbox is, does the most logical page open in a separate tab or window. I am troubled that we can't test the software prior to release to prod. @shnayder is this testing situation something that we can prioritize as important to fix?

**Comment by clintonb** [comment]
All help pages have opened in new tabs/windows since we first released.
That functionality has not changed. Only the destination has changed.

**Comment by rocha** [comment]
Nice. :rocket:

**Pull request merged**
