### PR TITLE
Fix syntax and typo in README.md

### PR DESCRIPTION
**Pull request by dlackty**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dlackty! I've created [OSPR-445](https://openedx.atlassian.net/browse/OSPR-445) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a [signed contributor agreement](http://code.edx.org/individual-contributor-agreement.pdf) or indicated your institutional affiliation and added yourself to the [AUTHORS](https://github.com/edx/edx-analytics-dashboard/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by clintonb** [comment]
:+1:

**Comment by sarina** [comment]
@clintonb - please don't merge PRs unless we triage them to you. In the case, the contributor didn't sign a contributor's agreement, so we can't take this patch until we have legal permission from him to use and republish his work.

**Comment by sarina** [comment]
@dlackty have you sent in a contributor's agreement yet, as the bot requests?

**Comment by sarina** [comment]
Also @clintonb we don't use the "open-source-contribution" label anymore. Please don't manually mess with the labels - the labels correspond to states in JIRA, and only JIRA transitions should change them.

**Comment by dlackty** [comment]
@sarina Just sent signed CA to jennifer at edx.org.

**Pull request merged**
