### PR TITLE
Upgraded edx-auth-backends to 1.0.2

### PR DESCRIPTION
**Pull request by clintonb**
LEARNER-693

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/analytics 

What is your process for deploying to stage/production? Ideally, I would like to get this deployed ASAP so that we can move forward with updating the authentication provider (LMS). See https://openedx.atlassian.net/browse/LEARNER-693 for details.

**Comment by thallada** [comment]
We just setup a GoCD pipeline that pushes to stage on merge to master and then one of us can push a button to push it to production.

**Comment by dsjen** [comment]
@clintonb -- looks like tests are failing, e.g.:

```
ERROR: test_timeout (analytics_dashboard.learner_analytics_api.v0.tests.test_views.LearnerListViewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/waffle/testutils.py", line 45, in _wrapped
    return func(*args, **kwargs)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/edx/app/insights/edx_analytics_dashboard/analytics_dashboard/learner_analytics_api/v0/tests/test_views.py", line 62, in test_timeout
    self.login()
  File "/edx/app/insights/edx_analytics_dashboard/analytics_dashboard/core/tests/test_views.py", line 36, in login
    assert self.client.login(username=self.user.username, password=self.PASSWORD), 'Login failed!'
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/test/client.py", line 596, in login
    user = authenticate(**credentials)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/social_core/backends/open_id_connect.py", line 49, in __init__
    super(OpenIdConnectAuth, self).__init__(*args, **kwargs)
TypeError: __init__() takes at least 2 arguments (1 given)
```

**Comment by dsjen** [comment]
@clintonb -- why was this PR merged?  There were no approvals.

**Comment by clintonb** [comment]
I informed the team of the intent to get this done ASAP. I received no
objections.

If you have questions about what changed in the library I'm happy to answer
them.
-- 
Clinton Blackburn

**Pull request merged**
