### PR TITLE
Engagement with Course Discussions

### PR DESCRIPTION
**Pull request by lamagnifica**
## [DOC-3426](https://openedx.atlassian.net/browse/DOC-3426)

Discussion activity over the last week is now one of the engagement metrics.
### Date Needed

Release is expected within the next few days.
### Reviewers

Possible roles follow. PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [x] Subject matter expert: @thallada 
- [x] Subject matter expert: @dsjen 
- [x] Doc team review (copy edit): @edx/doc
- [x] Product review: @katymyw
- [ ] Partner support: 
- [ ] PM review: 

FYI: Kate Venier
### Testing
- [x] Ran make html without warnings or errors
### Post-review
- [x] Add description to release notes task as a comment (DOC-3422)
- [ ] Squash commits

### CODE REVIEW

**Comment by thallada** [comment]
This looks good to me :+1:

**Review by dsjen — APPROVED** [review]
👍

**Comment by srpearce** [comment]
👍

**Comment by katymyw** [comment]
👍  Looks good!

**Comment by srpearce** [comment]
@dsjen or @thallada - Could you guys confirm that this documentation is still accurate (i.e., that nothing has changed) and that we should go ahead and merge it with this week's release?

**Comment by thallada** [comment]
@srpearce This documentation is still accurate. We just enabled this feature on production, so go ahead!

**Comment by srpearce** [comment]
@thallada Great, thanks!

**Pull request merged**
