### PR TITLE
Change the name of the environment variable that stores the config file ...

### PR DESCRIPTION
**Pull request by mulby**
...path

I suspect this ENV var conflicts with the API

@rocha @clintonb @dsjen

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by rocha** [comment]
My bad. :rocket:

**Comment by clintonb** [comment]
@mulby, are you going to merge this, or should it be closed?

**Comment by mulby** [comment]
hah, I forgot this was here

**Pull request merged**
