### PR TITLE
Update Learners lens copy

### PR DESCRIPTION
**Pull request by dan-f**
Update the learner lens copy on the course home page.

screen shot 2016-04-22 at 9 14 37 am

@dsjen please review
@lamagnifica and @shnayder FYI - this is the copy that you asked for :)

[AN-7011](https://openedx.atlassian.net/browse/AN-7011)

### CODE REVIEW

**Comment by lamagnifica** [comment]
:dancers: :+1: :smiley:

**Comment by brianhw** [comment]
This made me laugh when I first read it.  I interpreted it as "Who is engaged?  Isn't everyone?".

**Comment by dsjen** [comment]
Ha!  Love it.  👍

**Comment by dan-f** [comment]
hah, I like that @brianhw :)

**Pull request merged**
