### PR TITLE
Open release/koa.master

### PR DESCRIPTION
**Pull request by karthikyuvi**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @karthikyuvi! I've created [OSPR-5856](https://openedx.atlassian.net/browse/OSPR-5856) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@karthikyuvi Hello, is this PR intentional?

**Comment by karthikyuvi** [comment]
Yes

**Comment by nedbat** [comment]
Hi @karthikyuvi, Koa is currently unsupported since Lilac was released last week.  But beyond the question of which release is accepting fixes, we typically make changes to master first, and then back-port them.  And changes need to be explained.

What improvements do these changes make?

**Comment by nedbat** [comment]
@karthikyuvi This looks like it's meant for your own fork, not for edx.  Feel free to re-open this, and help us understand, if this is incorrect.

**Comment by openedx-webhooks** [comment]
@karthikyuvi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-dashboard&entry.867055334=https://github.com/edx/edx-analytics-dashboard/pull/1132&entry.1484655318=https://github.com/karthikyuvi&entry.752974735=2021-06-11+17:42&entry.1917517419=2021-06-22+17:31&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
