### PR TITLE
Using matching font for all items in lens dropdown menu

### PR DESCRIPTION
**Pull request by clintonb**
@rocha @dsjen

### CODE REVIEW

**Comment by clintonb** [comment]
Before
screen shot 2014-09-04 at 11 54 05 am

After
screen shot 2014-09-04 at 11 53 46 am

**Comment by clintonb** [comment]
@marcotuts @shnayder

**Comment by shnayder** [comment]
Overview is turned off via feature flag, right?  :+1: otherwise.

**Comment by clintonb** [comment]
Correct.

## 

Clinton Blackburn

**Pull request merged**
