### PR TITLE
Updated copy for answer distribution pages.

### PR DESCRIPTION
**Pull request by dsjen**
- Updated "update" message.
- Updated page title.
- Updated short problem description.
- Updated message for randomized problems.
- Updated chart tip message.

**Randomized Problem**
screen shot 2015-01-28 at 4 40 57 pm

**Chart**
screen shot 2015-01-28 at 4 42 58 pm

:eyes: @lamagnifica @rocha @shnayder @clintonb @andywaldrop :eyes:

### CODE REVIEW

**Comment by shnayder** [comment]
:ship: :+1: :rocket: :roller_coaster: :bear: :cookie: :sunflower: :sunrise_over_mountains:

**Comment by lamagnifica** [comment]
AN-4424: :+1: 
AN-4425: :+1: 
AN-4426: :+1:
AN-4427: dreadful nit, but is there any way to NOT include the informational tootip in the chart area for a randomized problem?
AN-4428: :+1:
AN-4429: :+1:

**Comment by dsjen** [comment]
@lamagnifica Can do -- removing the tooltip is a :cake: !

**Comment by andywaldrop** [comment]
:+1:

**Comment by clintonb** [comment]
:+1:

**Comment by rocha** [comment]
:rocket:

**Pull request merged**
