### PR TITLE
Integrate with Travis CI and coveralls.io

### PR DESCRIPTION
**Pull request by muhammad-ammar**
TE-475

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by benpatterson** [comment]
:+1: 

Could you file a ticket for adding acceptance tests?

**Comment by muhammad-ammar** [comment]
@benpatterson I will add the ticket.

Should i merge the PR?

**Comment by benpatterson** [comment]
Once you add the ticket, you can merge the PR. (Though, based on the grayed-out status, it looks like you may need to rebase or do a manual merge.)

**Pull request merged**
