### PR TITLE
Run modernize and isort commands for help.

### PR DESCRIPTION
**Pull request by andrey-canon**
## Description
run the following
- python-modernize -w analytics_dashboard/help/
- isort -rc analytics_dashboard/help/

### Reviewers
- [x] @morenol 
- [x]  Is this ready for edX's review?
- [ ] @jmbowman 

### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @andrey-canon! I've created [OSPR-4141](https://openedx.atlassian.net/browse/OSPR-4141) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by morenol** [comment]
LGTM

**Comment by natabene** [comment]
@jmbowman This is ready for your review.

**Review by jmbowman — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@andrey-canon 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-dashboard&entry.867055334=https://github.com/edx/edx-analytics-dashboard/pull/934&entry.1484655318=https://github.com/andrey-canon&entry.752974735=2020-03-02+21:33&entry.1917517419=2020-03-03+19:51&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
