### PR TITLE
Using Fork of django-dynamic-fixture

### PR DESCRIPTION
**Pull request by clintonb**
The nose plugin included with django-dynamic-fixture has a bug that results in its being loaded unnecessarily. I have forked the repository and fixed this bug. Until my PR is merged, we will use the fork. I also fixed a Pylint warning about a deprecated directive.

### CODE REVIEW

**Comment by clintonb** [comment]
@dsjen @benpatterson @rocha

**Comment by rocha** [comment]
:rocket:

Do you know why tests are failing?

**Comment by clintonb** [comment]
@rocha No, I think it's an issue with Jenkins. @dsjen just mentioned issues in Hipchat.

**Comment by rocha** [comment]
Alright

**Pull request merged**
