### PR TITLE
Updated django announcement to use pinax branch.

### PR DESCRIPTION
**Pull request by dsjen**
RahimovIR's PR (fixed django 1.6 compatibility issue) was merged to pinax.

@brianhw @mulby @jab5569

### CODE REVIEW

**Comment by dsjen** [comment]
This is failing because python-social-auth upgraded, which is a required by edx/auth-backends.  I'm looking into patching edx/auth-backends.

**Comment by dsjen** [comment]
https://github.com/edx/edx-analytics-dashboard/pull/299 will fix the build.

**Comment by brianhw** [comment]
Do we not need this anymore?

**Comment by dsjen** [comment]
I forgot about this!  I'll merge it in.

**Pull request merged**
