### PR TITLE
Run modernize and isort for core files.

### PR DESCRIPTION
**Pull request by andrey-canon**
## Descrition
run the following
- python-modernize -w analytics_dashboard/core/
- isort -rc analytics_dashboard/core/

### Reviewers
- [x] @morenol 
- [x]  Is this ready for edX's review?
- [ ] @jmbowman 
### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @andrey-canon! I've created [OSPR-4138](https://openedx.atlassian.net/browse/OSPR-4138) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by morenol** [comment]
LGTM

**Comment by natabene** [comment]
@andrey-canon Thank you for your contribution. I am queuing it for our review.

**Comment by natabene** [comment]
@andrey-canon Unfortunately, we don't accept contributions to this repo at this time. Sorry for not indicating it clearly upfront, we will fix it.

**Comment by openedx-webhooks** [comment]
@andrey-canon Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-dashboard&entry.867055334=https://github.com/edx/edx-analytics-dashboard/pull/932&entry.1484655318=https://github.com/andrey-canon&entry.752974735=2020-03-02+20:20&entry.1917517419=2020-03-02+21:56&entry.2133058324=No) so we can improve your experience in the future.

**Comment by felipemontoya** [comment]
Hello @natabene,

This PR and a few others that are still on WIP are being worked on as part of the epic https://openedx.atlassian.net/browse/BOM-1360 with the final goal of migrating insights to Django 2.2. This work is sponsored by edX.

Other than adding the Jira link in the PR cover letter, should we state this in another way in the PR?

**Review by jmbowman — APPROVED** [review]
@natabene I'll be reviewing most of these, let me know if you want them to add a label or such.  In practice, most of the PRs here and in edx-analytics-data-api for the next month will be part of this project.

**Comment by openedx-webhooks** [comment]
@andrey-canon 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-dashboard&entry.867055334=https://github.com/edx/edx-analytics-dashboard/pull/932&entry.1484655318=https://github.com/andrey-canon&entry.752974735=2020-03-02+20:20&entry.1917517419=2020-03-03+14:37&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
